[package]
name = "nurikabe"
version = "0.1.0"
edition = "2021"

[features]
default = ["display"]
display = ["colored"]

[dependencies]
colored = { version = "2", optional = true }
by_address = "1.0.4"
nom = "7.1.1"